### ISSUE TITLE
Story TODO

### ISSUE THREAD

**Issue by youbitchoc** [henpemaz/Rain-Meadow#498]
GAMEPLAY:
- [ ] vulture desync
  - also seem to pop out of pipes?
- [ ] invis creatures
  - particularly dropwigs, sometimes lizards and scavs
- [ ] creatures popping out of pipes causing physics engine lag
  - particularly noticeable in scav tolls
- [ ] duped toll pearlstrings
  - consider just not syncing for now
- [ ] slugpups  // dlc and not a priority

CAMPAIGN:
- [ ] ARTI ending
  - sync violence ending trigger for everyone
  - currently everyone just gets stuck on the continue screen?
  - continuing campaign doesn't respawn at throne, no king scav mask either
- [ ] RIV bitter aerie transition
  - should we let everyone have the gravity balls?
- [ ] SPEARMASTER fetch quest and ending
  - not sure how much isn't synced, will need testing
- [ ] SAINT iterator ascensions and ending
  - think currently host needs to be there to see it
  - make this an rpc? make the rpc generic?
    - we could introspect the deathpersistentsavestate savestring function to get the savestring
    - else would be nice to have a convenient dictionary so custom campaigns can just register there
- [ ] fix ascension blocking remote players from progressing?
  - or we could also just vanish remote players once they hit the void sea

OTHER:
- [ ] fix passages, only allow host to use
- [ ] sync creature kills and other statistics

**Comment by youbitchoc** [comment]
all special ending spawns are currently broken, we need host to use denpos from savestate and also some way to force denpos for everyone

should be safe to check if saved without readyForWin then force denpos

**Comment by FateUnix29** [comment]
give everyone the gravity balls, they'll need it
that or give everyone riv mobility (though some things, even with riv mobility, are better with grav ball of fun, mishap, and doom)

**Comment by youbitchoc** [comment]
- [ ] stuckdaddy
  - can we just not sync the ac?
