### ISSUE TITLE
Chat: To-Do

### ISSUE THREAD

**Issue by 6fears7** [henpemaz/Rain-Meadow#594]
- [x] Rebindable enter key
- [x] Update tutorial chat dialogue to use dynamic button
- [x] Event messages
- [x] Brighten dark usernames
- [x] Fix message positioning
- [x] New parent object for ChatTextBox
- [x] Remix to keep chat up

**Comment by SaddestUnderscore** [comment]
I can tackle those
